eureka:  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle8iDialect
spring.jpa.hibernate.ddl-auto = update
spring.datasource.username = rakeshreddy
spring.datasource.password = rakeshreddy
# Show or not log for each sql query\u200B
spring.jpa.show-sql = true
server.port = 8871
server.error.whitelabel.enabled=false
